language: ruby
rvm:
  - 2.7.2
  - 3.0.0
gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile
services:
  - postgresql
  - redis-server
env:
  - LIT_STORAGE=hash
  - LIT_STORAGE=redis
before_script:
  - cp test/dummy/config/database.yml.travis test/dummy/config/database.yml
  - psql -c 'create database lit_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate
script: "bundle exec rake test"
